// Code generated by github.com/dmitry-drozdov/gqlgen, DO NOT EDIT.

package out_omit_resolver_fields

type Base struct {
	StandardField string `json:"StandardField" database:"BaseStandardField"`
}

type Query struct {
}
