// Code generated by github.com/dmitry-drozdov/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/dmitry-drozdov/gqlgen/_examples/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location,omitempty"`
}

type Query struct {
}
